SELECT INFO.FLAVOR AS FLAVOR FROM FIRST_HALF HALF, ICECREAM_INFO INFO
WHERE HALF.TOTAL_ORDER > 3000
    AND HALF.FLAVOR = INFO.FLAVOR
    AND INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;